### ISSUE TITLE
Assignment2

### ISSUE THREAD

**Issue by blackboxlogic** [Daninblack/Cos470#2]
I don't see any proof of the output?

Regarding:
https://github.com/Daninblack/Cos470/blob/59513e3a100e945428ce2e4ffaf06b4f87aa7e88/Assignment2/DollarAddresses/DollarAddresses/appsettings.json#L3
This list is hard to understand because you've used an unusual delimiter. Looks like you're trying to remove the need to do URL encoding. "Hard to understand" means that your coworker is going to mess this up when they try to change it.

**Comment by Daninblack** [comment]
Sorry, I forgot to add the console output. I just added that now.

**Comment by Daninblack** [comment]
@blackboxlogic I just added the console output.

**Comment by Daninblack** [comment]
I made some changes to my program. I implemented URL encoding to my
program.and updated my appsetting.json
The console output has also been added.

**Comment by Daninblack** [comment]
@blackboxlogic I made some changes to my program. I implemented URL encoding to my program and updated my appsetting.json. 
The console output has also been added.
