### ISSUE TITLE
Assignment 3

### ISSUE THREAD

**Issue by blackboxlogic** [Daninblack/Cos470#4]
Your unit tests are great.

You should be using a .gitignore file.

This 20 wants to be configurable https://github.com/Daninblack/Cos470/blob/df98169a8af589b7baa8ca3445c34321852a025c/Assignment3/HaveWeMet/HaveWeMet/LocationHistoryHelperMethods.cs#L65

This 10 wants to be configurable https://github.com/Daninblack/Cos470/blob/df98169a8af589b7baa8ca3445c34321852a025c/Assignment3/HaveWeMet/HaveWeMet/LocationHistoryHelperMethods.cs#L93

Huh, didn't know there was something in the system libraries for calculating distance.

I don't think this does what you want it to https://github.com/Daninblack/Cos470/blob/df98169a8af589b7baa8ca3445c34321852a025c/Assignment3/HaveWeMet/HaveWeMet/LocationHistoryHelperMethods.cs#L54
Are you trying to reduce the resolution of the date to be whole days or whole seconds? Maybe add a specific test for your assumption.

I think you want to use your DateTimesCoincide() function, not checking for exact equality
https://github.com/Daninblack/Cos470/blob/df98169a8af589b7baa8ca3445c34321852a025c/Assignment3/HaveWeMet/HaveWeMet/LocationHistoryAnalysis.cs#L16

User interface code in the middle of your business logic https://github.com/Daninblack/Cos470/blob/df98169a8af589b7baa8ca3445c34321852a025c/Assignment3/HaveWeMet/HaveWeMet/LocationHistoryAnalysis.cs#L18

But really, all that is pretty minor and your code is well written.

Wait a second, this is O(n^2) https://github.com/Daninblack/Cos470/blob/df98169a8af589b7baa8ca3445c34321852a025c/Assignment3/HaveWeMet/HaveWeMet/LocationHistoryAnalysis.cs#L26

**Comment by Daninblack** [comment]
Issues have been addressed.

**Comment by blackboxlogic** [comment]
### Data model
yep
### Business logic
* The fuzzy-ness of the match isn't configurable: -2 pts
* UserInterface code in your business logic (Console.WriteLine()): -2 pts
### Tests
Your tests fail on my computer because you have hardcoded paths: -5 pts
### Api
I really like that your API supports multiple people ("Frank" and "Donnie").
I really like that your API supports multiple operations.
FYI you put the full paths to the file in your config file. Nice that it is configurable but if you had just 
Controller:
```
    var result = LocationHistoryAnalysis.HaveWeMet(locationHistory, locationHistory2);
    var date = LocationHistoryHelperMethods.UnixTimeStampToDateTime(result.timestampMs);
```
`HaveWeMet()` sometimes returns null, so this code will blow up if there is no match.
Null reference exception: -2 pts
Evidence of the API response: Yep
### Organization
Needs gitIgnore folders: -3 points
* bin
* obj
* .vs

**Comment by Daninblack** [comment]
@blackboxlogic I have made changes to this Assignment.

**Comment by blackboxlogic** [comment]
93/100
Fixed:
UserInterface code in your business logic (Console.WriteLine()): +2 pts
Your GitIgnore still isn't right. All those files are still being tracked by git.
Hardcoded path for tests: +5 pts
